// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGApXuYBvAhmHob4NwggnXr7C7ajxVFmc',
    appId: '1:1054238838352:android:8d282cf18168181c930b55',
    messagingSenderId: '1054238838352',
    projectId: 'shule360-7d263',
    storageBucket: 'shule360-7d263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_hmK5T6fg8sul87qLZsrzgTKxrCtIRg',
    appId: '1:1054238838352:ios:b76c4feb0267d50e930b55',
    messagingSenderId: '1054238838352',
    projectId: 'shule360-7d263',
    storageBucket: 'shule360-7d263.firebasestorage.app',
    iosBundleId: 'com.shule360.shule360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvDMSoetF7HlxwzdSPRE10MXB23btuGfQ',
    appId: '1:1054238838352:web:f5180d5d2c6bcd63930b55',
    messagingSenderId: '1054238838352',
    projectId: 'shule360-7d263',
    authDomain: 'shule360-7d263.firebaseapp.com',
    storageBucket: 'shule360-7d263.firebasestorage.app',
    measurementId: 'G-QGHJFS7D4E',
  );
}
